ci:
  autoupdate_schedule: monthly

default_language_version:
  python: python3.14

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: end-of-file-fixer
    exclude: |
      (?x)^(
        example/example/static/ext/debug\.js
        |src/django_htmx/static/django_htmx/(htmx|htmax)-[24](\.min)?\.js
        |src/django_htmx/static/django_htmx/ext/[a-z0-9-]+-[24](\.min)?\.js
      )$
  - id: trailing-whitespace
    exclude: |
      (?x)^(
        src/django_htmx/static/django_htmx/(htmx|htmax)-[24](\.min)?\.js
        |src/django_htmx/static/django_htmx/ext/[a-z0-9-]+-[24](\.min)?\.js
      )$
- repo: https://github.com/crate-ci/typos
  rev: c132f8b9e3ac7f8f0625490b1cb5b906d1d6a63a  # frozen: v1
  hooks:
  - id: typos
    exclude: |
      (?x)^(
        .*\.svg
        |src/django_htmx/static/django_htmx/(htmx|htmax)-[24](\.min)?\.js
        |src/django_htmx/static/django_htmx/ext/[a-z0-9-]+-[24](\.min)?\.js
      )$
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: 3b42b9776870badc9eaffdef9a4a0834b764d87c  # frozen: v2.29.3
  hooks:
  - id: pyproject-fmt
- repo: https://github.com/tox-dev/tox-ini-fmt
  rev: 241ced4140307006cfd8b2b9ccfd43b1139cfe4a  # frozen: 1.9.0
  hooks:
  - id: tox-ini-fmt
- repo: https://github.com/rstcheck/rstcheck
  rev: 27a8027d6c6df787891a01b76e8298bac493fb58  # frozen: v6.3.0
  hooks:
  - id: rstcheck
    additional_dependencies:
    - sphinx==8.1.3
    - tomli==2.2.1
- repo: https://github.com/sphinx-contrib/sphinx-lint
  rev: c883505f64b59c3c5c9375191e4ad9f98e727ccd  # frozen: v1.0.2
  hooks:
  - id: sphinx-lint
- repo: https://github.com/adamchainz/django-upgrade
  rev: e668ea858b908d23a9702b24214f4fc5d07ed50f  # frozen: 1.32.0
  hooks:
  - id: django-upgrade
- repo: https://github.com/adamchainz/blacken-docs
  rev: dda8db18cfc68df532abf33b185ecd12d5b7b326  # frozen: 1.20.0
  hooks:
  - id: blacken-docs
    additional_dependencies:
    - black==25.1.0
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 321478e58f4938179c6b86e4ddfa923d1547a49b  # frozen: v0.16.6
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 7ff8d35ae36a7d2b968f2f90b4c723e292e594ee  # frozen: v2.3.1
  hooks:
  - id: mypy
    additional_dependencies:
    - django-stubs==6.1.0
    - types-python-dateutil
- repo: https://github.com/adamchainz/djade-pre-commit
  rev: 52a7ce253113456c2a1113186a4a19b15c8b68af  # frozen: 1.9.0
  hooks:
  - id: djade
